sudo: required

services:
- docker

script:
- >
- docker build -t glongzh/kubeadm-version:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push glongzh/kubeadm-version:$TRAVIS_BRANCH
- docker run --rm --name=kubeadm-version glongzh/kubeadm-version:$TRAVIS_BRANCH kubeadm config images list
